#!/bin/sh -e
#
# Script to import code from the A Transfer Protocol (ATP) library
#

usage() {
	echo <<EOF
Usage: $0 SRCECTORY

	Imports source files from the given directory, which should be
	the top level directory from the zipfile provided by Votsh
EOF
}

if [ "$#" != 1 ]; then
	echo Need exactly one argument
	usage
	exit 1
fi

SRC=$1
TARGET=$(cd $(dirname $0); pwd)
if ! [ -d "$SRC" ]; then
	echo Not a directory: $SRC
	usage
	exit 1
fi

for d in nwk phy hal sys; do
	if ! [ -d "$SRC/$d" ]; then
		echo $SRC does not look like a valid ATP directory, $SRC/$d missing
		exit 1
	fi
done

copy() {
	FROM="$1"
	TO="$2"


	if [ -d "$TO" ]; then
		# Remove any old files
		rm -f "$TO"/*
	else
		mkdir -p "$TO"
	fi

	cp "$FROM/src"/* "$TO"
	cp "$FROM/inc"/* "$TO"

	dos2unix --quiet "$TO"/*.h "$TO"/*.c
	sed -i -r 's%^#include ["<](atp)(.*)[">]$%#include "../\1/\1\2"%' "$TO"/*.h "$TO"/*.c
	# Add extern "C" to header files to allow including them from C++
	sed -i -r '1i #ifdef __cplusplus\nextern "C" {\n#endif' "$TO"/*.h
	sed -i -r '$a #ifdef __cplusplus\n}\n#endif' "$TO"/*.h
}

copy "$SRC/atp" "$TARGET/src/atp"

# Edit sysConfig.h to include a config.h from the root of this library.
# This should allow editing the config.h, without the risk of a sketch
# accidentally including it or this script overwriting it.
sed -i -r 's%^#include "config.h"%#include "../../../config.h"%' "$TARGET/src/atp/sysConfig.h"

